In [8]:
import pandas as pd
df1 = pd.read_csv("titanic_cleaned.csv")
df2 = pd.read_csv("ticket_fares.csv")

In [9]:
df3 = pd.merge(df1, df2, on='Ticket')
df3

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare_x,FamilySize,Embarked,IsAlone,Fare_y
0,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,1,S,0,7.2500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,1,C,0,71.2833
2,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,0,S,1,7.9250
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,1,S,0,53.1000
4,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,1,S,0,53.1000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1588,888,1,1,"Graham, Miss. Margaret Edith",female,19,0,0,112053,30.0000,0,S,1,30.0000
1589,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,21,1,2,W./C. 6607,23.4500,3,S,0,23.4500
1590,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,21,1,2,W./C. 6607,23.4500,3,S,0,23.4500
1591,890,1,1,"Behr, Mr. Karl Howell",male,26,0,0,111369,30.0000,0,C,1,30.0000
1592,891,0,3,"Dooley, Mr. Patrick",male,32,0,0,370376,7.7500,0,Q,1,7.7500

In [12]:
age_labels = ['Child', 'Teen', 'Adult', 'Senior']
age_bins = [0, 16, 25, 50, 100]
df3['AgeGroup'] = pd.cut(df3['Age'], bins = age_bins, labels = age_labels, right = True)
survival_rate = df3.groupby(['Sex', 'AgeGroup'], observed= True)['Survived'].mean()
df3
print(survival_rate)

Sex     AgeGroup
female  Child       0.478261
        Teen        0.638095
        Adult       0.739623
        Senior      0.933333
male    Child       0.253086
        Teen        0.145062
        Adult       0.250000
        Senior      0.100000
Name: Survived, dtype: float64

In [ ]:
with open('report.txt', 'w') as f:
    f.write("The anaylsis shows that women and children had higher survival rate than men." \
    "The survival rate of women ranges from 47.8% for child to 93.3% for seniors. On the other" \
    "hand the survival rate for men ranges from 10% for seniors to 25.3% for children. However " \
    "in females the children had the least survival rate compared to men where children had the " \
    "higest survival rate. The data supports the Women first hypothesis but it not supports children" \
    "first for female category")

In [19]:
class_survival = df3.groupby("Pclass")['Survived'].mean()
print(class_survival)
fare_labels = ['Low', 'Medium', 'High', 'Very High']
df3['FareBin'] = pd.qcut(df3['Fare_x'], 4, labels = fare_labels)
fare_survival = df3.groupby('FareBin', observed=True)['Survived'].mean()
print(fare_survival)
df3

Pclass
1    0.689055
2    0.480000
3    0.239057
Name: Survived, dtype: float64
FareBin
Low          0.229426
Medium       0.441687
High         0.336449
Very High    0.609418
Name: Survived, dtype: float64

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare_x,FamilySize,Embarked,IsAlone,Fare_y,AgeGroup,FareBin
0,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,1,S,0,7.2500,Teen,Low
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,1,C,0,71.2833,Adult,Very High
2,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,0,S,1,7.9250,Adult,Low
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,1,S,0,53.1000,Adult,High
4,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,1,S,0,53.1000,Adult,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1588,888,1,1,"Graham, Miss. Margaret Edith",female,19,0,0,112053,30.0000,0,S,1,30.0000,Teen,High
1589,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,21,1,2,W./C. 6607,23.4500,3,S,0,23.4500,Teen,Medium
1590,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,21,1,2,W./C. 6607,23.4500,3,S,0,23.4500,Teen,Medium
1591,890,1,1,"Behr, Mr. Karl Howell",male,26,0,0,111369,30.0000,0,C,1,30.0000,Adult,High
1592,891,0,3,"Dooley, Mr. Patrick",male,32,0,0,370376,7.7500,0,Q,1,7.7500,Adult,Low

In [ ]:
with open('report.txt', 'a') as f:
    f.write('The data supports the wealth hypothesis as the survival rate as in Passenger class' \
    'the survival rate ranges from 23.9% for class 3 to 68.9% for class 1. The survival rate ' \
    'increases as class increases. In Farebin the survival rate ranges from 22.9% for low fare ' \
    'to 60.9% for high fare. It increases for each fare class.')